### ISSUE TITLE
Panels are derivative works of Fundamental panels

### ISSUE THREAD

**Issue by AndrewBelt** [Aepelzen/AepelzensModules#13]
Gate Sequencer and Quad Sequencer still resemble Fundamental panels and are subject for removal from the VCV community database.

According to the Fundamental license (https://github.com/VCVRack/Fundamental#license), you may not create derivative works of Fundamental panels.

The CLOCK, RUN, RESET, and EXT CLK sections of both panels need to be changed to your original work. Reply to this once fixed and the plugin can stay in the community database.

Note: I have also recently removed https://github.com/Aepelzen/AepelzensParasites from the community database until the IP violation is fixed. https://github.com/Aepelzen/AepelzensParasites/issues/4

**Comment by Aepelzen** [comment]
Did you even look at the modules, or just the screenshot? The Gate Sequencer has been updated more than 2 months ago. Updating the screenshot for changed fonts seemed a bit over the top, so I kept the old one. I now also "fixed" the Quad Sequencer (in the 0.6-dev branch which will become the master branch when rack 0.6 is released).

But please remove my plugins from your shop anyway.

Regarding my other modules. I already told you that I consider those panels covered by the original CC-license and therefore free to use.

**Comment by AndrewBelt** [comment]
This panel is a derivative, and the two screenshots are infringements. https://github.com/Aepelzen/AepelzensModules/blob/master/res/QuadSeq.svg
https://github.com/Aepelzen/AepelzensModules/blob/master/images/screenshot.png
The other modules are fine.

I've removed the listing from the community repository, but you still need to remove the graphics from this GitHub repo.

**Comment by AndrewBelt** [comment]
I see that Quad Sequencer has been fixed in the 0.6dev branch. I'll re-add when Rack 0.6 is released. Thanks.

**Comment by Aepelzen** [comment]
Please don't add my plugins to your module manager.
