### ISSUE TITLE
quadseq output behavior

### ISSUE THREAD

**Issue by joopvdl** [Aepelzen/AepelzensModules#17]
glad to see aepelzens back in 6.0!
But I have one question. You changed output behaviour so the seq. won't output when stopped. But I find it very practical for setting values when it continues to output in stopped mode.
I was curious why you changed the behaviour (maybe there's something to learn here for me)
Perhaps you can add a right-click option to switch between modes?

thanks, Joop

**Comment by Aepelzen** [comment]
I thought that would be more reasonable behaviour, so the sequencer doesn't interfere with the rest of the patch when it's stopped. You would not want to have a static offset from the sequencer while tuning your oscillators for example. If you want to set exact values in the sequencer itself (when stopped) that should be even easier now using the step-select buttons at the bottom. Once you hit one of these the sequencer will also output it's signals and continue doing so until you start it.

**Comment by joopvdl** [comment]
Ah, I missed those completely (thought they were gate/trigger buttons) :)
Thanks, now I like your stuff even more....
