### ISSUE TITLE
drum sampler build fail

### ISSUE THREAD

**Issue by davephillips** [Aepelzen/AepelzensModules#19]
Fedora 23 Linux
Rack master (0.6.x)
GCC 5.3.1

Possibly a compiler issue:

g++ -Wsuggest-override -std=c++11 -DSLUG="Aepelzens Modules" -fPIC -I../../include -I../../dep/include -DVERSION=0.6.0dev -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/Sampler.cpp.o src/Sampler.cpp
src/Sampler.cpp: In member function ‘rack::Frame<2ul> AeSampler::interpolateFrame(rack::Frame<2ul>*, float)’:
src/Sampler.cpp:213:31: error: cannot convert ‘float*’ to ‘double*’ for argument ‘2’ to ‘double modf(double, double*)’
     float frac = modf(phase,&i);
                               ^
../../compile.mk:61: recipe for target 'build/src/Sampler.cpp.o' failed
make: *** [build/src/Sampler.cpp.o] Error 1

Any suggestions for fixing ?

**Comment by Aepelzen** [comment]
That's a pretty old compiler you got there. I'm surprised you can build ABI-compatible plugins with that. Please try the latest commit, that should fix your issue.

And just out of curiosity, do you build Rack yourself? And if so, can you load binary plugins with that?

**Comment by davephillips** [comment]
Got it, thanks a lot ! Builds and loads fine now, I'm looking forward to testing the drum sampler.

Yes, I build Rack myself. I have to tweak the source a tiny bit to fix some includes, otherwise it's an easy build. Re: binary plugins: Some work without trouble, but for some I have to provide a compliant libstdc++ that I dropped into dep/lib (and which works only as long as Rack uses LD_LIBRARY_PATH).

**Comment by Aepelzen** [comment]
Allright, good to know. Have fun with the sampler and please let me know if you find any bugs or have some suggestions.
