### ISSUE TITLE
No an issue a suggestion

### ISSUE THREAD

**Issue by ShofB** [Aepelzen/AepelzensModules#2]
Very nice, thanks for the mods, I really like the length and probability per channel, very nice.   But people always want more so one thing that would really make the grid seq more powerful would be to add cv for the length and prob on each channel.  No one does that  ( or at least not that I'm aware of ).  This would make for some interesting applications in setting polyrhythms.

**Comment by martin-lueders** [comment]
I agree that a CV control of the probability would be great.

**Comment by Aepelzen** [comment]
I thought about that too but figured that modulating the length might be a bit too much. Different clock rates and lengths can allready produce pretty complex results. Modulating the probabilities might be a good idea though. I will probably try that soon.

**Comment by Aepelzen** [comment]
CV control for probabilities added.
