### ISSUE TITLE
Erwin quantizer

### ISSUE THREAD

**Issue by Eurikon** [Aepelzen/AepelzensModules#23]
Hi there,
i get an error with the Erwin quantizer when trying to load a scala .scl micro-tuning file

**Comment by Eurikon** [comment]
hi there, why is this issue closed without a reply comment?

**Comment by Aepelzen** [comment]
Because this is not an issue.

**Comment by Eurikon** [comment]
Hi, thanks for answering here. 
ok can you please then tell me why i am getting an error prompt?
Can this module load .scl files? Cause it seems not, and in the manual is not mentioned that it can not load Scala files. 
Just trying to get this work with my favorite Quantizer.

**Comment by Aepelzen** [comment]
LOL, this is hilarious. It never occured to me to describe all the things a module can not do in the manual. So just to save you some time, Erwin also can not load pdfs, isos and most other filetypes. It can however export it's scales, so if you try really hard you can probably figure out what kind of file the import function expects.

**Comment by Eurikon** [comment]
wow..
