### ISSUE TITLE
Issue with Burst

### ISSUE THREAD

**Issue by martin-lueders** [Aepelzen/AepelzensModules#3]
I noticed that Burst sometimes does not work, until you activate 'initialize' from the menu. I had the same issue with some of my modules, and it is most likely due to the fact that some variables are not initialized.

If you initialize them in the 'reset()' routine, you need to call this routine from your constructor.
I just had a look at your code, and your value for 'delta' is not defined before you call reset().

Cheers,
Martin

**Comment by Aepelzen** [comment]
Thanks for the info. I assumed that onSampleRateChange() would be called during initialisation.
Will be fixed in the next update.

**Comment by metaphorz** [comment]
Confirmed. I just made for Mac OSX, and selecting Burst crashes Rack. Do you want the trace?

**Comment by Aepelzen** [comment]
That is probably another issue, the initialisation problem should allready be fixed (unless i overlooked some other uninitialised variables).
I don't have OSX so i won't be able to reproduce any issues with that but feel free to post whatever useful information you might have.

**Comment by metaphorz** [comment]
I'll start a new issue - sounds right, then this can be closed.

**Comment by metaphorz** [comment]
Just rebuilt at work - same OS (High Sierra). Everything works fine now, so do not know what happened when at home. I also see Manifold! I take it back. Something weird is going on-I'll investigate and create an issue if I cannot figure it out
