### ISSUE TITLE
mac binaries

### ISSUE THREAD

**Issue by cfoulc** [Aepelzen/AepelzensModules#6]
[Aepelzens-0.5.1-mac.zip](https://github.com/Aepelzen/AepelzensModules/files/1630854/Aepelzens-0.5.1-mac.zip)

used this makefile : 
[Makefile.zip](https://github.com/Aepelzen/AepelzensModules/files/1630855/Makefile.zip)

**Comment by nay-seven** [comment]
thanks !

**Comment by Aepelzen** [comment]
Thanks for doing this.

For everybody else reading this I want to make it clear that i neither built nor tested this, so use at your own risk.

**Comment by Aepelzen** [comment]
outdated
