### ISSUE TITLE
Aepelzens Modules: version number?

### ISSUE THREAD

**Issue by DomiKamu** [Aepelzen/AepelzensModules#7]
Hi,

It will useful to indicate the version of your modules, because it's not easy to check if they're updated or not (I'm using Excel spreadsheet as database to reference all installed modules for my VCV Rack).

Thank you very much in advance.

**Comment by Edin72** [comment]
How do you install them anyway?! Could someone help me? I'm new...

**Comment by DomiKamu** [comment]
@Edin72 please create a new issue, because this issue isn't related to installation. Thanks in advance.

**Comment by DomiKamu** [comment]
@Edin72 please create a new issue in this repository, and delete your message above, because you're doing a request for assistance not related to this issue I've opened. Thanks in advance.

**Comment by Aepelzen** [comment]
Hi, I'm not sure how to do that. I haven't done any releases so what would i even assign a version number to? If you need a version number for your spreadsheet you could just use the latest commit-hash or date.

**Comment by DomiKamu** [comment]
Ah yes, you're right, I see 0 release (only source is provided). For compile (Windows) myself I've added VERSION = 0.5.1 into MakeFile... Okay, we can close this issue. Cheers.
