### ISSUE TITLE
Erwin Suggestion

### ISSUE THREAD

**Issue by bubbleandsquawk** [Aepelzen/AepelzensModules#8]
It's so great to have a multichannel quantizer available, but would you by any chance consider adding gate ins/outs to it? Similar to the ADDAC Systems Quantizer.

**Comment by Aepelzen** [comment]
Hi, i haven't thought about that but it sounds interesting.
I assume the gate in would work like a sample and hold, right? If so, what would be the advantage of having a gate in over just using one of the many sample-and-hold modules?
And what is the gate out supposed to do, just pass the gate signal?

**Comment by phdsg** [comment]
think this is what they are looking for: https://youtu.be/ddsL6xC8Eyw?t=7m5s

**Comment by bubbleandsquawk** [comment]
yeah gate in is very much like a sample and hold. I suppose the benefit of having it contained within the quantisation module is a convenience, or workflow improvement. Less clicking around, less modules, more music faster! Also, say I wanted to take a single continuous CV like a slewed random or cross modulated LFO or something, and I want to extract several different but related variations, I could mult the CV to the various inputs and feed them different gate patterns to extract different patterns. 

As for gate outputs, in an an analog system one reason you would want this is to ensure that the gates you are sending to say, envelopes are in sync with the quantised notes. Maybe not so important in a digital system, I’m not sure. But say I was once again sending the quantiser a continuous CV and rather than using the gate ins to determine the rhythm and quantisation points of the extracted melody, I wanted to produce a gate for every moment the quantiser latched onto a value. I could then send a gate for every note extracted.

**Comment by Aepelzen** [comment]
I'm not sure if I see the inclusion of sample and hold functionality as a benefit. Combining specialised modules is the main advantage of going modular after all, but i might give this another thought. 

The output idea seems more interesting to me allthough i'm wondering how you would use it. Assuming you feed in a continuous cv-signal and create gates whenever the quantiser latches on to a new value, that would only create sequences that play the scale up and down (without ever skipping a note or introducing any melodic variation), wouldn't it? That sounds pretty boring, or am I missing something?

**Comment by bubbleandsquawk** [comment]
Well, the same could be said of having multiple quantisers within a module. The benefit here being that instead of pulling up four of the same module to achieve a result, you only need one. Obviously in rack we aren’t limited by the number of modules we can use but less modules does certainly make for a less cluttered interface. It’s not as though there are varying behaviours between sample and holds either. 

As for the gate out, say you have the scale set to just a triad, and sent a triangle wave it could work like arpeggiator, and if sent a complex and evolving cv it will generate variation over the octaves. Say I mix several different shaped LFOs and use them as the CV, there will be all kinds of jumps and discontinuities.

**Comment by bubbleandsquawk** [comment]
Here's an example of the type of thing that gate outs is useful for:
https://www.dropbox.com/s/pqsbbqr7s7lnqmz/complexquant.vcv?dl=0

If there were gates, I could send them to an envelope and have a bit more control over the duration of the notes.

**Comment by Aepelzen** [comment]
K, got it. I am going to do the 0.6 update first but after that i will try the gate out thing.

**Comment by Aepelzen** [comment]
Check out the latest commit. It might not be exactly what you were hoping for but I thought the gate out idea might be useful for other things too. So, in the spirit of modularisation I turned it into it's own module. It has 4 channels and should pair well with Erwin.

**Comment by bubbleandsquawk** [comment]
I'd have no idea what to do with that. I'll have to wait until a binary comes around to see. Thanks!
